### ISSUE TITLE
`shards install`: Error in shard.yml: missing required attribute: name

### ISSUE THREAD

**Issue by grokify** [grokify/crystal-pingpong#3]
The following `shard.yml` file results in the following:

`shard.yml` file:

```yaml
dependencies:
  pingpong:
    github: grokify/crystal-pingpong
```

command:

```bash
% shards install
Error in shard.yml: missing required attribute: name at line 4, column 1

  2.   pingpong:
  3.     github: grokify/crystal-pingpong
     ^

Resolving dependencies
```

**Comment by grokify** [comment]
Minimal `shard.yml` file needs `name` and `version` attributes:

```yaml
name: testing
version: 0.1.0

dependencies:
  pingpong:
    github: grokify/crystal-pingpong
```
